import { Community, FloorPlan, Metro, QuickMoveInLot } from './types'

export const METROS: Metro[] = [
  {
    id: 'houston',
    name: 'Houston Metro',
    state: 'TX',
    code: 'HOU',
    communityCount: 6,
    planCount: 18,
    inventoryCount: 12,
    startingPrice: 259900,
    description: 'Premier acreage and master-planned communities across Katy, Montgomery, Conroe, and Richmond.',
    heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 'dfw',
    name: 'Dallas - Fort Worth',
    state: 'TX',
    code: 'DFW',
    communityCount: 4,
    planCount: 14,
    inventoryCount: 8,
    startingPrice: 319900,
    description: 'High-growth North Texas communities in Celina, Waxahachie, Forney, and Denton County.',
    heroImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 'austin',
    name: 'Austin - San Marcos',
    state: 'TX',
    code: 'ATX',
    communityCount: 2,
    planCount: 10,
    inventoryCount: 4,
    startingPrice: 389900,
    description: 'Hill Country vistas and tech-corridor convenience in Liberty Hill, Kyle, and Dripping Springs.',
    heroImage: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 'phoenix',
    name: 'Phoenix East Valley',
    state: 'AZ',
    code: 'PHX',
    communityCount: 2,
    planCount: 8,
    inventoryCount: 3,
    startingPrice: 429900,
    description: 'Desert modern architecture with mountain backdrops across Queen Creek and Buckeye.',
    heroImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80',
  },
]

export const COMMUNITIES: Community[] = [
  {
    id: 'riverwood-ranch',
    name: 'Riverwood Ranch',
    slug: 'riverwood-ranch',
    metroId: 'houston',
    city: 'Angleton',
    county: 'Brazoria County',
    state: 'TX',
    zip: '77515',
    priceRange: '$279k – $410k',
    startingPrice: 279900,
    description: 'Picturesque community featuring half-acre homesites, oak tree preserves, and direct access to state parks.',
    heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    amenities: [
      { name: 'Resort Swimming Pool', icon: 'Waves', description: 'Zero-entry resort pool with poolside cabanas and splash pad.' },
      { name: 'Catch & Release Lakes', icon: 'Fish', description: 'Three stocked fishing lakes with scenic walking piers.' },
      { name: 'Nature Trail Network', icon: 'TreePine', description: 'Over 4 miles of paved hike & bike trails winding through native pines.' },
      { name: 'Pickleball Courts', icon: 'Trophy', description: 'Lit dual pickleball and basketball courts for evening matches.' },
    ],
    schoolDistrict: 'Angleton ISD (Exemplary STEAM Campus)',
    hoaDues: '$650 / Year',
    taxRate: '2.14% (No MUD Tax)',
    salesCounselor: {
      name: 'Marcus Sterling',
      phone: '(832) 555-0142',
      email: 'msterling@hogghomes.com',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    },
    activeFloorPlanIds: ['san-jacinto', 'brazos', 'travis', 'alamo'],
    moveInReadyCount: 4,
  },
  {
    id: 'grand-oaks-reserve',
    name: 'Grand Oaks Reserve',
    slug: 'grand-oaks-reserve',
    metroId: 'houston',
    city: 'Cleveland',
    county: 'Liberty County',
    state: 'TX',
    zip: '77328',
    priceRange: '$259k – $390k',
    startingPrice: 259900,
    description: 'Master-planned golf resort community with a 9-hole championship course, community clubhouse, and tennis pavilion.',
    heroImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80',
    amenities: [
      { name: '9-Hole Golf Course', icon: 'Flag', description: 'Professionally manicured golf course with pro shop.' },
      { name: 'Community Clubhouse & Bistro', icon: 'Coffee', description: 'Full clubhouse dining with covered veranda patio.' },
      { name: 'Kids Adventure Playground', icon: 'Sparkles', description: 'Custom timber playground with safety turf.' },
    ],
    schoolDistrict: 'Cleveland ISD',
    hoaDues: '$720 / Year',
    taxRate: '2.32%',
    salesCounselor: {
      name: 'Elena Vance',
      phone: '(832) 555-0189',
      email: 'evance@hogghomes.com',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    },
    activeFloorPlanIds: ['alamo', 'san-jacinto', 'colorado'],
    moveInReadyCount: 3,
  },
  {
    id: 'canyon-falls-estates',
    name: 'Canyon Falls Estates',
    slug: 'canyon-falls-estates',
    metroId: 'dfw',
    city: 'Celina',
    county: 'Collin County',
    state: 'TX',
    zip: '75009',
    priceRange: '$349k – $549k',
    startingPrice: 349900,
    description: 'North Dallas corridor luxury living on 70-foot lots with rolling topography and blue-ribbon schools.',
    heroImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80',
    amenities: [
      { name: 'Club Canyon Fitness Center', icon: 'Dumbbell', description: '24/7 fitness facility with Peloton suites and yoga lawn.' },
      { name: 'Bark Park & Agility Course', icon: 'Dog', description: 'Double-gated dog park with shaded seating and wash station.' },
      { name: 'Community Event Pavilion', icon: 'Flame', description: 'Outdoor fireplace with BBQ rotisseries for neighborhood socials.' },
    ],
    schoolDistrict: 'Celina ISD (A+ Rated)',
    hoaDues: '$950 / Year',
    taxRate: '2.28%',
    salesCounselor: {
      name: 'Devon Richardson',
      phone: '(972) 555-0199',
      email: 'drichardson@hogghomes.com',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    },
    activeFloorPlanIds: ['brazos', 'travis', 'colorado', 'rio-grande'],
    moveInReadyCount: 5,
  },
  {
    id: 'highland-vista',
    name: 'Highland Vista',
    slug: 'highland-vista',
    metroId: 'austin',
    city: 'Liberty Hill',
    county: 'Williamson County',
    state: 'TX',
    zip: '78642',
    priceRange: '$389k – $620k',
    startingPrice: 389900,
    description: 'Hill Country sanctuary with limestone facades, panoramic sunset lookouts, and high-efficiency standard solar pre-wire.',
    heroImage: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=1600&q=80',
    amenities: [
      { name: 'Sunset Hill Lookout Deck', icon: 'Eye', description: 'Observation overlook facing the San Gabriel River valley.' },
      { name: 'Resort Infinity Pool', icon: 'Waves', description: 'Negative-edge swimming pool overlooking protected greenbelt.' },
      { name: 'EV Fast-Charge Hub', icon: 'Zap', description: 'Community ultra-fast charging bays for electric vehicles.' },
    ],
    schoolDistrict: 'Liberty Hill ISD',
    hoaDues: '$850 / Year',
    taxRate: '1.98% (Low Tax Advantage)',
    salesCounselor: {
      name: 'Sarah Chen',
      phone: '(512) 555-0167',
      email: 'schen@hogghomes.com',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    },
    activeFloorPlanIds: ['travis', 'colorado', 'rio-grande'],
    moveInReadyCount: 3,
  },
  {
    id: 'sonoran-ridge',
    name: 'Sonoran Ridge',
    slug: 'sonoran-ridge',
    metroId: 'phoenix',
    city: 'Queen Creek',
    county: 'Maricopa County',
    state: 'AZ',
    zip: '85142',
    priceRange: '$429k – $680k',
    startingPrice: 429900,
    description: 'Southwestern contemporary design nestled against the San Tan Mountains with expansive multi-slide patio glass doors.',
    heroImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80',
    amenities: [
      { name: 'San Tan Mountain Trails', icon: 'Mountain', description: 'Direct trailhead access to 10,000+ acres of regional park.' },
      { name: 'Desert Oasis Splash Park', icon: 'Droplets', description: 'Shaded water park with misting stations and lounge seating.' },
      { name: 'Stargazing Amphitheater', icon: 'Moon', description: 'Dark-sky compliant community observation circle.' },
    ],
    schoolDistrict: 'Queen Creek Unified',
    hoaDues: '$920 / Year',
    taxRate: '1.45%',
    salesCounselor: {
      name: 'Tate MacIntyre',
      phone: '(480) 555-0131',
      email: 'tmacintyre@hogghomes.com',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    },
    activeFloorPlanIds: ['travis', 'colorado', 'rio-grande'],
    moveInReadyCount: 2,
  },
]

export const FLOOR_PLANS: FloorPlan[] = [
  {
    id: 'the-san-jacinto',
    name: 'The San Jacinto',
    slug: 'san-jacinto',
    series: 'Heritage Collection',
    basePrice: 279900,
    sqft: 1640,
    bedrooms: 3,
    bathrooms: 2,
    halfBaths: 0,
    stories: 1,
    garageBays: 2,
    popularTag: 'Most Efficient Single-Story',
    elevations: [
      {
        id: 'A',
        name: 'Elevation A',
        styleName: 'Modern Farmhouse',
        description: 'Crisp vertical board & batten siding, matte black industrial fixtures, cedar gable brackets, and a welcoming covered front porch.',
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'B',
        name: 'Elevation B',
        styleName: 'Hill Country Craftsman',
        description: 'Hand-cut Austin white limestone wainscoting, tapered square column stone pedestals, and heritage shakes.',
        imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'C',
        name: 'Elevation C',
        styleName: 'Transitional Contemporary',
        description: 'Low-pitched roofline, clean horizontal masonry panels, floor-to-ceiling Low-E glass, and minimalist fascia.',
        imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    rooms: [
      { room: 'Great Room', dimensions: '16\' 4" × 18\' 8"', features: ['10-ft Volume Ceiling', 'Recessed LED Lighting', 'Overlooking Patio'] },
      { room: 'Primary Suite', dimensions: '14\' 2" × 15\' 6"', features: ['En-suite Spa Bath', 'Walk-in Dual Closet', 'Oversized Vanity'] },
      { room: 'Kitchen & Dining Island', dimensions: '12\' 0" × 14\' 6"', features: ['8-ft Quartz Prep Island', 'Walk-in Pantry', 'Whirlpool Stainless Appliance Suite'] },
      { room: 'Bedroom 2', dimensions: '11\' 0" × 11\' 8"', features: ['Walk-in Closet', 'Adjacent Full Bath'] },
      { room: 'Bedroom 3 / Study', dimensions: '10\' 6" × 11\' 4"', features: ['French Door Option', 'Cat6 Pre-wired'] },
      { room: 'Covered Rear Patio', dimensions: '10\' 0" × 16\' 0"', features: ['Gas Stub for BBQ', 'Outdoor Ceiling Fan Pre-wire'] },
      { room: '2-Car Garage', dimensions: '20\' 0" × 21\' 4"', features: ['240V NEMA 14-50 EV Charger', 'Wi-Fi Smart Opener'] },
    ],
    features: [
      'Single-Story Open-Concept Flow with Zero Wasted Hallway Space',
      'Designer Quartz Countertops throughout Kitchen & Baths',
      'Carrier 16-SEER High Efficiency HVAC with Ecobee Smart Thermostat',
      'Tankless Rinnai On-Demand Gas Water Heater in Garage',
      'Smart Home Tech Package (Video Doorbell, Keyless Lock, Smart Hub)',
    ],
    availableInCommunities: ['riverwood-ranch', 'grand-oaks-reserve'],
  },
  {
    id: 'the-brazos',
    name: 'The Brazos',
    slug: 'brazos',
    series: 'Signature Series',
    basePrice: 349900,
    sqft: 2280,
    bedrooms: 4,
    bathrooms: 2,
    halfBaths: 1,
    stories: 2,
    garageBays: 2,
    popularTag: 'Top-Selling Family Plan',
    elevations: [
      {
        id: 'A',
        name: 'Elevation A',
        styleName: 'Modern Farmhouse',
        description: 'Striking monochrome exterior with dark standing-seam metal awning accents and carriage-style overhead door.',
        imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'B',
        name: 'Elevation B',
        styleName: 'Texas Craftsman',
        description: 'Rich earth-tone brick paired with cast stone key headers and decorative cedar shaker gables.',
        imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'C',
        name: 'Elevation C',
        styleName: 'Urban Modern',
        description: 'Linear architectural massing, smooth stucco finish coat, and oversized clerestory accent windows.',
        imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    rooms: [
      { room: 'Great Room (2-Story)', dimensions: '18\' 0" × 20\' 6"', features: ['18-ft Soaring Ceilings', 'Wall of Windows', 'Optional Gas Fireplace'] },
      { room: 'Primary Suite (1st Floor)', dimensions: '15\' 0" × 17\' 4"', features: ['Private Retreat Wing', 'Freestanding Soaking Tub', 'Walk-in Dual Shower'] },
      { room: 'Chef\'s Kitchen', dimensions: '13\' 6" × 16\' 0"', features: ['Built-in Wall Oven & Microwave', 'Walk-in Butler\'s Pantry', 'Under-cabinet LED Lighting'] },
      { room: 'Second Floor Game Room', dimensions: '15\' 4" × 16\' 8"', features: ['Open Balcony Railing to Great Room below', 'Media Pre-wire'] },
      { room: 'Bedroom 2 & 3', dimensions: '11\' 6" × 12\' 0"', features: ['Jack-and-Jill Bath Connection'] },
      { room: 'Bedroom 4', dimensions: '11\' 0" × 11\' 8"', features: ['En-suite Full Bath Access'] },
      { room: 'Deep Covered Patio', dimensions: '12\' 0" × 18\' 0"', features: ['Outdoor Living Connection', 'Gas & Cable Pre-wire'] },
    ],
    features: [
      'Downstairs Primary Retreat for ultimate privacy from secondary bedrooms',
      'Expansive Upstairs Game Room & Flex Space for entertaining',
      'Walk-in Butler\'s Pantry with secondary prep surface',
      'Dual-zone Smart Climate Controls (independent upstairs/downstairs)',
      'Engineered Post-Tension Foundation with 10-Year Structural Warranty',
    ],
    availableInCommunities: ['riverwood-ranch', 'canyon-falls-estates'],
  },
  {
    id: 'the-travis',
    name: 'The Travis',
    slug: 'travis',
    series: 'Signature Series',
    basePrice: 389900,
    sqft: 2150,
    bedrooms: 4,
    bathrooms: 3,
    halfBaths: 0,
    stories: 1,
    garageBays: 3,
    popularTag: 'Executive Single-Story • 3-Car Garage',
    elevations: [
      {
        id: 'A',
        name: 'Elevation A',
        styleName: 'Hill Country Modern',
        description: 'Chiseled limestone exterior, charcoal slate standing-seam metal roofs, and natural cedar columns.',
        imageUrl: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'B',
        name: 'Elevation B',
        styleName: 'Modern Farmhouse',
        description: 'Stately symmetrical board-and-batten facade with dark bronze metal awnings and 8-foot stained front door.',
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'C',
        name: 'Elevation C',
        styleName: 'Contemporary Prairie',
        description: 'Broad low-pitch eaves, horizontal cast-stone accents, and bronze mullion windows.',
        imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    rooms: [
      { room: 'Grand Gathering Room', dimensions: '19\' 0" × 21\' 0"', features: ['11-ft Coffered Ceilings', '12-ft Center-Slide Glass Doors'] },
      { room: 'Primary Sanctuary', dimensions: '16\' 0" × 18\' 0"', features: ['Walk-through Double Shower', 'Dual Granite Vanities', 'Direct Laundry Room Pass-Through'] },
      { room: 'Gourmet Kitchen', dimensions: '14\' 0" × 16\' 6"', features: ['10-ft Seamless Quartz Island', '36" 5-Burner Gas Cooktop', 'Walk-in Pantry'] },
      { room: 'Private In-Law Suite', dimensions: '12\' 6" × 13\' 0"', features: ['Private En-suite 3rd Bathroom', 'Walk-in Closet'] },
      { room: '3-Car Tandem Garage', dimensions: '30\' 0" × 22\' 0"', features: ['Shop / Boat Storage Bay', 'Heavy-Duty 240V Outlet'] },
    ],
    features: [
      'True 3-Car Garage with dedicated workshop space or third vehicle stall',
      'Private In-Law / Guest Suite with private full bath',
      'Direct laundry room access through the Primary Suite closet',
      '12-ft Multi-Slide Glass Doors opening out to covered lanai',
      'Zip System Weatherization & Advantech Subflooring',
    ],
    availableInCommunities: ['highland-vista', 'canyon-falls-estates', 'sonoran-ridge'],
  },
  {
    id: 'the-colorado',
    name: 'The Colorado',
    slug: 'colorado',
    series: 'Pinnacle Collection',
    basePrice: 479900,
    sqft: 3120,
    bedrooms: 5,
    bathrooms: 3,
    halfBaths: 1,
    stories: 2,
    garageBays: 3,
    popularTag: '5 Bedrooms • Media Room Included',
    elevations: [
      {
        id: 'A',
        name: 'Elevation A',
        styleName: 'Modern Farmhouse Luxury',
        description: 'Imposing two-story gable profile, black window sashes, wraparound front porch, and zinc accents.',
        imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'B',
        name: 'Elevation B',
        styleName: 'Craftsman Estate',
        description: 'Full-height masonry chimney breast, exposed cedar rafter tails, and double sidelight entrance.',
        imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'C',
        name: 'Elevation C',
        styleName: 'Modern European',
        description: 'High-pitch hip roof, light-colored tumbled brick, recessed entryway, and black iron lanterns.',
        imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    rooms: [
      { room: 'Executive Great Room', dimensions: '20\' 0" × 22\' 4"', features: ['20-ft Cathedral Ceilings', 'Gas Log Fireplace with Hearth'] },
      { room: 'Primary Wing', dimensions: '16\' 6" × 19\' 0"', features: ['Sitting Area Alcove', 'Zero-Threshold Shower', 'Dual Custom Walk-ins'] },
      { room: 'Private Theater / Media', dimensions: '14\' 0" × 17\' 0"', features: ['Sound Insulation Tier 2', 'Tiered Seating Pre-wire', '7.1 Surround Pre-wire'] },
      { room: 'Dedicated Home Office', dimensions: '12\' 0" × 13\' 6"', features: ['French Glass Double Doors', 'Custom Built-in Bookcase Wall'] },
      { room: 'Bedrooms 2, 3, 4 & 5', dimensions: '12\' 0" × 13\' 0"', features: ['Each with Walk-in Closets'] },
    ],
    features: [
      'Dedicated Sound-Insulated Cinema / Media Room on 2nd floor',
      'Downstairs Dedicated Study with private courtyard views',
      'Oversized 3-Car Side-Entry Garage with painted epoxy floor',
      'Dual Tankless Water Heaters with instant recirculating loop',
      'Integrated Security & Automation Hub with sensor pre-wire',
    ],
    availableInCommunities: ['canyon-falls-estates', 'highland-vista', 'sonoran-ridge'],
  },
  {
    id: 'the-alamo',
    name: 'The Alamo',
    slug: 'alamo',
    series: 'Heritage Collection',
    basePrice: 254900,
    sqft: 1480,
    bedrooms: 3,
    bathrooms: 2,
    halfBaths: 0,
    stories: 1,
    garageBays: 2,
    popularTag: 'Best Value Starter Home',
    elevations: [
      {
        id: 'A',
        name: 'Elevation A',
        styleName: 'Modern Farmhouse',
        description: 'Warm siding palette, painted shutters, carriage garage door, and entry awning.',
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'B',
        name: 'Elevation B',
        styleName: 'Classic Brick Traditional',
        description: 'Four-sided brick masonry skirt with keystones and insulated energy star fiberglass door.',
        imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'C',
        name: 'Elevation C',
        styleName: 'Contemporary Craftsman',
        description: 'Clean horizontal siding lines with cedar porch columns and bronze hardware.',
        imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    rooms: [
      { room: 'Open Living & Dining', dimensions: '15\' 0" × 22\' 0"', features: ['9-ft Ceilings', 'Luxury Vinyl Plank Flooring', 'Abundant Natural Light'] },
      { room: 'Primary Bedroom', dimensions: '13\' 4" × 14\' 8"', features: ['Walk-in Closet', '5-ft Walk-in Shower'] },
      { room: 'Galley Kitchen', dimensions: '10\' 0" × 12\' 0"', features: ['Granite Countertops', 'Stainless Steel Range', 'Tall Pantry'] },
      { room: 'Bedrooms 2 & 3', dimensions: '10\' 6" × 11\' 0"', features: ['Spacious Closets', 'Shared Hall Full Bath'] },
    ],
    features: [
      'Accessible price point under $260k without sacrificing construction quality',
      'Luxury Vinyl Plank (LVP) resilient flooring in all wet areas and living room',
      'Low-E Double Pane Argon-Filled Windows for maximum Texas heat deflection',
      'Complete Builder Warranty (1-Yr Workmanship, 2-Yr Systems, 10-Yr Structural)',
    ],
    availableInCommunities: ['grand-oaks-reserve', 'riverwood-ranch'],
  },
  {
    id: 'the-rio-grande',
    name: 'The Rio Grande',
    slug: 'rio-grande',
    series: 'Pinnacle Collection',
    basePrice: 529900,
    sqft: 3450,
    bedrooms: 5,
    bathrooms: 4,
    halfBaths: 0,
    stories: 2,
    garageBays: 3,
    popularTag: 'Flagship Luxury Estate',
    elevations: [
      {
        id: 'A',
        name: 'Elevation A',
        styleName: 'Modern Farmhouse Manor',
        description: 'Grand scale white board-and-batten facade with double gables and black casement architectural windows.',
        imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'B',
        name: 'Elevation B',
        styleName: 'Hill Country Heritage',
        description: 'Chopped limestone, exposed Douglas fir timbers, standing-seam porch accents, and iron hardware.',
        imageUrl: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'C',
        name: 'Elevation C',
        styleName: 'Desert Contemporary',
        description: 'Warm stucco tones with basalt stone cladding, flat parapet profiles, and floating overhangs.',
        imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    rooms: [
      { room: 'Great Hall Living', dimensions: '22\' 0" × 24\' 0"', features: ['22-ft Volume Ceilings', 'Multi-Slide Fleetwood Pocket Doors'] },
      { room: 'Executive Primary Suite', dimensions: '17\' 0" × 20\' 0"', features: ['Fireplace', 'Heated Bathroom Floors', 'Boutique Dressing Closet'] },
      { room: 'Prep Scullery / Dirty Kitchen', dimensions: '9\' 0" × 12\' 0"', features: ['Secondary Dishwasher & Sink', 'Floor-to-Ceiling Storage'] },
      { room: 'Upstairs Media Lounge', dimensions: '16\' 0" × 18\' 0"', features: ['Wet Bar & Beverage Fridge Pre-wire'] },
    ],
    features: [
      'Show Kitchen + Hidden Butler\'s Prep Scullery for seamless hosting',
      'Dual Primary Bedrooms (one on main level, one upstairs guest suite)',
      'Smart home automated shades, lighting scenes, and audio zoning',
      'Covered Outdoor Veranda with built-in stainless gas grill & granite counter',
    ],
    availableInCommunities: ['canyon-falls-estates', 'highland-vista', 'sonoran-ridge'],
  },
]

export const QUICK_MOVE_IN_LOTS: QuickMoveInLot[] = [
  {
    id: 'lot-42-whispering-pines',
    lotNumber: 'Lot 42',
    streetAddress: '1042 Whispering Pines Way',
    communityId: 'riverwood-ranch',
    communityName: 'Riverwood Ranch',
    metroId: 'houston',
    floorPlanId: 'the-brazos',
    floorPlanName: 'The Brazos',
    elevation: 'A',
    sqft: 2280,
    bedrooms: 4,
    bathrooms: 2.5,
    stories: 2,
    garageBays: 2,
    originalPrice: 369900,
    currentPrice: 349900,
    savingsAmount: 20000,
    constructionStage: 'Move-In Ready Today',
    constructionProgressPercent: 100,
    estimatedCompletion: 'Ready Now (Close in 14 Days)',
    incentive: '⭐ 4.99% Fixed 30-Year Rate Lock + $12,500 Closing Cost Credit',
    highlightFeatures: [
      'Cul-de-sac Oversized Lot (0.42 Acres)',
      'Upgraded 42" Snow White Shaker Cabinets with Matte Black Pulls',
      'Calacatta Gold Quartz Waterfall Island',
      'Full Yard Sod & Automatic Irrigation System Included',
    ],
    heroImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
    interiorImages: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=80',
    ],
  },
  {
    id: 'lot-18-timber-ridge',
    lotNumber: 'Lot 18',
    streetAddress: '4819 Timber Ridge Circle',
    communityId: 'riverwood-ranch',
    communityName: 'Riverwood Ranch',
    metroId: 'houston',
    floorPlanId: 'the-san-jacinto',
    floorPlanName: 'The San Jacinto',
    elevation: 'B',
    sqft: 1640,
    bedrooms: 3,
    bathrooms: 2,
    stories: 1,
    garageBays: 2,
    originalPrice: 289900,
    currentPrice: 279900,
    savingsAmount: 10000,
    constructionStage: 'Move-In Ready Today',
    constructionProgressPercent: 100,
    estimatedCompletion: 'Ready Now',
    incentive: '⭐ $10,000 Flex Cash toward Rate Buydown or Blinds/Refrigerator',
    highlightFeatures: [
      'Greenbelt Backyard with No Rear Neighbors',
      'Upgraded Wood-Look Ceramic Plank Tile in Common Areas',
      'Full Gutters and 6-ft Cedar Privacy Fence',
    ],
    heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    interiorImages: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    ],
  },
  {
    id: 'lot-77-fairway-view',
    lotNumber: 'Lot 77',
    streetAddress: '1105 Fairway View Blvd',
    communityId: 'grand-oaks-reserve',
    communityName: 'Grand Oaks Reserve',
    metroId: 'houston',
    floorPlanId: 'the-alamo',
    floorPlanName: 'The Alamo',
    elevation: 'A',
    sqft: 1480,
    bedrooms: 3,
    bathrooms: 2,
    stories: 1,
    garageBays: 2,
    originalPrice: 264900,
    currentPrice: 254900,
    savingsAmount: 10000,
    constructionStage: 'Drywall',
    constructionProgressPercent: 75,
    estimatedCompletion: 'Target Next Month (Approx 30 Days)',
    incentive: '⭐ $7,500 Towards Closing Costs with Hogg Mortgage Partners',
    highlightFeatures: [
      'Golf Course Green View from Back Porch',
      'Zero Down USDA Eligible Financing Location',
      'Smart Thermostat & Ring Video Doorbell Pro Installed',
    ],
    heroImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80',
    interiorImages: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
    ],
  },
  {
    id: 'lot-88-canyon-crest',
    lotNumber: 'Lot 88',
    streetAddress: '3104 Canyon Crest Run',
    communityId: 'canyon-falls-estates',
    communityName: 'Canyon Falls Estates',
    metroId: 'dfw',
    floorPlanId: 'the-colorado',
    floorPlanName: 'The Colorado',
    elevation: 'A',
    sqft: 3120,
    bedrooms: 5,
    bathrooms: 3.5,
    stories: 2,
    garageBays: 3,
    originalPrice: 499900,
    currentPrice: 479900,
    savingsAmount: 20000,
    constructionStage: 'Move-In Ready Today',
    constructionProgressPercent: 100,
    estimatedCompletion: 'Ready Now',
    incentive: '⭐ 4.875% Special Builder Incentive Rate Lock',
    highlightFeatures: [
      '3-Car Tandem Garage with Epoxy Finish',
      'Upgraded Media Room with 7.1 Speaker Package',
      'Commercial Style Gas Range & Double Ovens',
      'Walk to Celina Blue-Ribbon Elementary',
    ],
    heroImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80',
    interiorImages: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
    ],
  },
  {
    id: 'lot-12-hilltop-terrace',
    lotNumber: 'Lot 12',
    streetAddress: '722 Hilltop Terrace Court',
    communityId: 'highland-vista',
    communityName: 'Highland Vista',
    metroId: 'austin',
    floorPlanId: 'the-travis',
    floorPlanName: 'The Travis',
    elevation: 'A',
    sqft: 2150,
    bedrooms: 4,
    bathrooms: 3,
    stories: 1,
    garageBays: 3,
    originalPrice: 414900,
    currentPrice: 389900,
    savingsAmount: 25000,
    constructionStage: 'Move-In Ready Today',
    constructionProgressPercent: 100,
    estimatedCompletion: 'Ready Now',
    incentive: '⭐ $15,000 Flex Cash + Free Level 2 EV Charger Installed',
    highlightFeatures: [
      'Hill Country Sunset Panorama Decking',
      'In-Law Guest Suite with Private 3rd Bath',
      'Spray Foam Insulation with Low HERS Index (54)',
    ],
    heroImage: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=1600&q=80',
    interiorImages: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    ],
  },
  {
    id: 'lot-55-saguaro-pass',
    lotNumber: 'Lot 55',
    streetAddress: '20814 E Saguaro Pass Lane',
    communityId: 'sonoran-ridge',
    communityName: 'Sonoran Ridge',
    metroId: 'phoenix',
    floorPlanId: 'the-rio-grande',
    floorPlanName: 'The Rio Grande',
    elevation: 'C',
    sqft: 3450,
    bedrooms: 5,
    bathrooms: 4,
    stories: 2,
    garageBays: 3,
    originalPrice: 559900,
    currentPrice: 529900,
    savingsAmount: 30000,
    constructionStage: 'Framing',
    constructionProgressPercent: 45,
    estimatedCompletion: 'Target Completion: December 2026',
    incentive: '⭐ Early Buyer Design Studio Allowance: $20,000 Custom Selections',
    highlightFeatures: [
      'Backs to San Tan Mountain Regional Reserve',
      '12-ft Center-Pocket Glass Patio Doors',
      'Custom Prep Scullery with Second Dishwasher',
    ],
    heroImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80',
    interiorImages: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=80',
    ],
  },
]

export const ARCHITECTURE_METRICS = [
  {
    metric: 'Initial TTFB (Time to First Byte)',
    legacyValue: '1,840 ms (WordPress CMS / Apache PHP)',
    nextjsValue: '42 ms (Edge RSC + Vercel Cache)',
    gain: '43.8× Faster',
  },
  {
    metric: 'Client Bundle Hydration Payload',
    legacyValue: '1.42 MB (JQuery, Enqueued Plugins, Unused Assets)',
    nextjsValue: '86 KB (Isolated Leaf Components)',
    gain: '94% Reduction',
  },
  {
    metric: 'Faceted Filter Response Latency',
    legacyValue: '820 ms (AJAX Round-Trip to MySQL)',
    nextjsValue: '< 12 ms (In-Memory React 19 State)',
    gain: 'Instant Micro-Interaction',
  },
  {
    metric: 'Cumulative Layout Shift (CLS)',
    legacyValue: '0.245 (Late-loading images, shifting banners)',
    nextjsValue: '0.000 (Explicit aspect-ratios & static geometry)',
    gain: 'Rock Solid CWV Score',
  },
  {
    metric: 'CRM Tour Dispatch Pipeline',
    legacyValue: 'Email notification scraping / Manual cron',
    nextjsValue: 'Zod-validated Server Action + HMAC Webhook',
    gain: 'Zero Lead Leakage',
  },
]
