import { PacsPreset } from './pacs-types'

export const TARGET_GENETEC_FIELDS = [
  {
    key: 'FirstName',
    label: 'First Name',
    required: true,
    description: 'Cardholder legal given name',
    schemaType: 'VARCHAR(50)',
  },
  {
    key: 'LastName',
    label: 'Last Name',
    required: true,
    description: 'Cardholder family surname',
    schemaType: 'VARCHAR(50)',
  },
  {
    key: 'BadgeID',
    label: 'Badge / Card Number',
    required: true,
    description: 'Credential identifier or Wiegand bitmask',
    schemaType: 'VARCHAR(64)',
  },
  {
    key: 'FacilityCode',
    label: 'Facility Code',
    required: false,
    description: 'Wiegand site code (0-255 or custom)',
    schemaType: 'INT32',
  },
  {
    key: 'Email',
    label: 'Email Address',
    required: false,
    description: 'Corporate email for mobile credentials',
    schemaType: 'VARCHAR(100)',
  },
  {
    key: 'AccessGroup',
    label: 'Access Level Group',
    required: false,
    description: 'Assigned perimeter and interior clearance groups',
    schemaType: 'VARCHAR(255)',
  },
  {
    key: 'Status',
    label: 'Cardholder Status',
    required: true,
    description: 'Active or Inactive provisioning state',
    schemaType: 'ENUM(Active, Inactive)',
  },
]

export const PACS_PRESETS: PacsPreset[] = [
  {
    id: 'lenel',
    name: 'Lenel OnGuard 8.1',
    version: 'v8.1.440',
    vendorBadge: 'MS SQL Server',
    description: 'Relational BADGE & EMP tables with discrete Facility Codes and semicolon-delimited clearance groups.',
    sourceColumns: [
      'EMPID',
      'FIRSTNAME',
      'LASTNAME',
      'BADGE_STATUS',
      'CARDNUM',
      'FACILITY_CODE',
      'ISSUE_CODE',
      'ACCESS_LEVEL_ID',
      'DEPT_NAME',
      'EXPIRATION_DATE',
    ],
    sampleRecords: [
      {
        EMPID: '10842',
        FIRSTNAME: 'Marcus',
        LASTNAME: 'Vance',
        BADGE_STATUS: '1',
        CARDNUM: '45821',
        FACILITY_CODE: '102',
        ISSUE_CODE: '1',
        ACCESS_LEVEL_ID: 'AL_HQ_STANDARD;AL_DATACENTER_TIER1',
        DEPT_NAME: 'Global Infrastructure',
        EXPIRATION_DATE: '2028-12-31',
      },
      {
        EMPID: '10843',
        FIRSTNAME: 'Elena',
        LASTNAME: 'Reyes',
        BADGE_STATUS: '1',
        CARDNUM: '45822',
        FACILITY_CODE: '102',
        ISSUE_CODE: '1',
        ACCESS_LEVEL_ID: 'AL_HQ_STANDARD;AL_EXEC_SUITE',
        DEPT_NAME: 'Executive Office',
        EXPIRATION_DATE: '2027-06-30',
      },
      {
        EMPID: '10844',
        FIRSTNAME: 'David',
        LASTNAME: 'Kowalski',
        BADGE_STATUS: '0',
        CARDNUM: '39104',
        FACILITY_CODE: '042',
        ISSUE_CODE: '2',
        ACCESS_LEVEL_ID: 'AL_PERIMETER_ONLY',
        DEPT_NAME: 'Field Operations',
        EXPIRATION_DATE: '2024-01-15',
      },
      {
        EMPID: '10845',
        FIRSTNAME: 'Aisha',
        LASTNAME: 'Patel',
        BADGE_STATUS: '1',
        CARDNUM: '58209',
        FACILITY_CODE: '102',
        ISSUE_CODE: '1',
        ACCESS_LEVEL_ID: 'AL_HQ_STANDARD;AL_LAB_CLEANROOM',
        DEPT_NAME: 'Biomedical R&D',
        EXPIRATION_DATE: '2029-09-01',
      },
    ],
    defaultMappings: {
      FirstName: 'FIRSTNAME',
      LastName: 'LASTNAME',
      BadgeID: 'CARDNUM',
      FacilityCode: 'FACILITY_CODE',
      AccessGroup: {
        type: 'access-flatten',
        source: 'ACCESS_LEVEL_ID',
        inputDelimiter: ';',
        outputDelimiter: ', ',
      },
      Status: {
        type: 'status-normalize',
        source: 'BADGE_STATUS',
        activeValues: ['1', 'Active'],
      },
    },
  },
  {
    id: 'dna_fusion',
    name: 'Open Options DNA Fusion',
    version: 'v8.4.1',
    vendorBadge: 'Windows PACS Service',
    description: 'Enterprise credential export with composite Wiegand descriptors, pipe delimiters, and internal personnel keys.',
    sourceColumns: [
      'BadgeNumber',
      'InternalNumber',
      'LastName',
      'FirstName',
      'AccessLevelList',
      'CardType',
      'EmailAddress',
      'ActiveState',
    ],
    sampleRecords: [
      {
        BadgeNumber: '98412',
        InternalNumber: 'INT-004921',
        LastName: 'Chen',
        FirstName: 'Li Wei',
        AccessLevelList: 'Campus_Perimeter|Main_Server_Room|Exec_Elevators',
        CardType: 'HID_H10301_26Bit',
        EmailAddress: 'liwei.chen@enterprise-defense.com',
        ActiveState: 'True',
      },
      {
        BadgeNumber: '98413',
        InternalNumber: 'INT-004922',
        LastName: 'Holloway',
        FirstName: 'Sarah',
        AccessLevelList: 'Campus_Perimeter|Logistics_Dock',
        CardType: 'HID_H10301_26Bit',
        EmailAddress: 's.holloway@enterprise-defense.com',
        ActiveState: 'True',
      },
      {
        BadgeNumber: '98414',
        InternalNumber: 'INT-004923',
        LastName: 'Nakamura',
        FirstName: 'Kenji',
        AccessLevelList: 'Campus_Perimeter|SOC_Command_Center',
        CardType: 'HID_Corporate1000_35Bit',
        EmailAddress: 'k.nakamura@enterprise-defense.com',
        ActiveState: 'False',
      },
    ],
    defaultMappings: {
      FirstName: 'FirstName',
      LastName: 'LastName',
      BadgeID: 'BadgeNumber',
      Email: 'EmailAddress',
      AccessGroup: {
        type: 'access-flatten',
        source: 'AccessLevelList',
        inputDelimiter: '|',
        outputDelimiter: ', ',
      },
      Status: {
        type: 'status-normalize',
        source: 'ActiveState',
        activeValues: ['True', 'true', '1'],
      },
    },
  },
  {
    id: 'amag',
    name: 'AMAG Technology Symmetry',
    version: 'v9.4.2',
    vendorBadge: 'Multi-Node SQL',
    description: 'UK & US enterprise PACS database with discrete Forename/Surname, custom Facility Codes, and status codes (0=Active, 1=Lost, 2=Term).',
    sourceColumns: [
      'CardHolder_ID',
      'Forename',
      'Surname',
      'CardNumber',
      'PIN',
      'Company',
      'CardStatus',
      'ClearanceGroup',
      'FacilityCode',
    ],
    sampleRecords: [
      {
        CardHolder_ID: 'CH-88319',
        Forename: 'Dominic',
        Surname: 'Sterling',
        CardNumber: '12984',
        PIN: '4912',
        Company: 'Apex Cybernetics',
        CardStatus: '0',
        ClearanceGroup: 'Level 4 Restricted',
        FacilityCode: '077',
      },
      {
        CardHolder_ID: 'CH-88320',
        Forename: 'Beatrice',
        Surname: 'Ward',
        CardNumber: '12985',
        PIN: '8831',
        Company: 'Apex Cybernetics',
        CardStatus: '0',
        ClearanceGroup: 'Level 2 Facilities',
        FacilityCode: '077',
      },
      {
        CardHolder_ID: 'CH-88321',
        Forename: 'Julian',
        Surname: 'Monroe',
        CardNumber: '12986',
        PIN: '1092',
        Company: 'Apex Cybernetics',
        CardStatus: '2',
        ClearanceGroup: 'Terminated',
        FacilityCode: '077',
      },
    ],
    defaultMappings: {
      FirstName: 'Forename',
      LastName: 'Surname',
      BadgeID: 'CardNumber',
      FacilityCode: 'FacilityCode',
      AccessGroup: 'ClearanceGroup',
      Status: {
        type: 'status-normalize',
        source: 'CardStatus',
        activeValues: ['0'],
      },
    },
  },
  {
    id: 'ccure',
    name: 'Software House C•CURE 9000',
    version: 'v2.90 SP3',
    vendorBadge: 'Johnson Controls',
    description: 'Partitioned personnel records with clearance hierarchies, discrete personnel IDs, and comma lists.',
    sourceColumns: [
      'PersonnelID',
      'CH_First_Name',
      'CH_Last_Name',
      'Card_Number',
      'FacilityCode',
      'Personnel_Type',
      'Card_Status',
      'Clearances',
    ],
    sampleRecords: [
      {
        PersonnelID: 'P-99214',
        CH_First_Name: 'Tariq',
        CH_Last_Name: 'Al-Mansoor',
        Card_Number: '30491',
        FacilityCode: '140',
        Personnel_Type: 'Full-Time Engineer',
        Card_Status: 'ACTIVE',
        Clearances: 'L1-Lobby, L2-EastWing, L3-SOC',
      },
      {
        PersonnelID: 'P-99215',
        CH_First_Name: 'Rachel',
        CH_Last_Name: 'Greenberg',
        Card_Number: '30492',
        FacilityCode: '140',
        Personnel_Type: 'Security Director',
        Card_Status: 'ACTIVE',
        Clearances: 'L1-Lobby, Master-All-Doors',
      },
      {
        PersonnelID: 'P-99216',
        CH_First_Name: 'Mateo',
        CH_Last_Name: 'Cruz',
        Card_Number: '30493',
        FacilityCode: '140',
        Personnel_Type: 'Contractor',
        Card_Status: 'DISABLED',
        Clearances: 'L1-Lobby',
      },
    ],
    defaultMappings: {
      FirstName: 'CH_First_Name',
      LastName: 'CH_Last_Name',
      BadgeID: 'Card_Number',
      FacilityCode: 'FacilityCode',
      AccessGroup: 'Clearances',
      Status: {
        type: 'status-normalize',
        source: 'Card_Status',
        activeValues: ['ACTIVE', 'Active'],
      },
    },
  },
]
